export const GET_WOMENS_ERROR = "GET_TODO_ERROR";
export const GET_WOMENS_SUCCESS = "GET_WOMENS_SUCCESS";
export const GET_WOMENS_LOADING = "GET_WOMENS_LOADING";
export const GET_WOMENS_SUCCESS1 = "GET_WOMENS_SUCCESS1";